export const STORE_RECIPIENT_GENDER = 'STORE_RECIPIENT_GENDER';
export const STORE_RECIPIENT_AGE = 'STORE_RECIPIENT_AGE';
export const STORE_RECIPIENT_RELATIONSHIP = 'STORE_RECIPIENT_RELATIONSHIP';
export const STORE_RECIPIENT_OCASSION = 'STORE_RECIPIENT_OCASSION';
export const STORE_RECIPIENT_PRICE = 'STORE_RECIPIENT_PRICE';