export const STORE_SELECTED_MAIN_CATEGORIES = 'STORE_SELECTED_MAIN_CATEGORIES';
export const STORE_RELEVENT_SUB_CATEGORIES = 'STORE_RELEVENT_SUB_CATEGORIES';

export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_ALL_CATEGORIES_SUCCESS = 'FETCH_ALL_CATEGORIES_SUCCESS';
export const FETCH_ALL_CATEGORIES_FAILURE = 'FETCH_ALL_CATEGORIES_FAILURE';

export const SEARCH_MAIN_CATEGORIES = 'SEARCH_MAIN_CATEGORIES';
export const SEARCH_SUB_CATEGORIES = 'SEARCH_SUB_CATEGORIES';